# Generated by Django 6.0.1 on 2026-01-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
