# Generated by Django 6.0.1 on 2026-02-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
