# Generated by Django 6.0.1 on 2026-02-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
